name: Sync with Hugging Face Hub

on:
  push:
    branches:
      - main
    paths:
      - examples/github_runner_app/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync with Hugging Face
      uses: nateraw/huggingface-sync-action@v0.0.2
      with:
        github_repo_id: huggingface/fuego
        huggingface_repo_id: nateraw/fuego
        repo_type: space
        space_sdk: gradio
        subdirectory: examples/github_runner_app
      env:
        hf_token: ${{ secrets.HF_TOKEN }}
